version: "3"
services:
  nginx:
      image: nginx
      container_name: 'nginx'
      depends_on:
        - frontend
        - backend
      links:
        - backend
      volumes:
        - ./frontend/src/app/services:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8080:80"
  frontend:
    build:
      context: ./frontend
    container_name: "frontend-fs"
    volumes:
      - ./frontend/src/app/services:/app/www
  backend:
    build:
      context: ./backend
    container_name: "backend-fs"
    ports:
      - "8081:3333"