version: "3"
services:
  nginx:
    build:
        context: ./frontend
    container_name: 'nginx'
    depends_on:
        - backend
    links:
        - backend
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8080:80"
  backend:
    build:
        context: ./backend
    container_name: "backend-fs"
    ports:
      - "8081:3333"