version: "3"
services:
  nginx:
      image: nginx
      container_name: 'nginx'
      hostname: localhosts
      depends_on:
        - backend
      links:
        - backend
      volumes:
        - ./frontend/www:/var/www/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
  backend:
    build:
      context: ./backend
    container_name: "backend-fs"
    ports:
      - "8081:3333"